name: Bug report
description: Create a report to help us improve
title: "bug: <your description here>"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### 🐛 Bug Report

        Thanks for helping improve the project! Please fill out the form below.

        > 💡 **Note:** A bug is a disagreement between actual and documented behavior, or an inaccurate error message.
        > Please file a [request](https://github.com/Deltakit/deltakit/issues/new?template=request.md) if the
        > documentation does not define the expected behavior, if you disagree with the documented behavior, or if you
        > are asking for a new feature or performance improvement.
        > Please use the [test failure form](https://github.com/Deltakit/deltakit/issues/new?template=test_failure.yml)
        > if you're a contributor seeing a test failure in main, either locally or on CI.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        A description of the bug.
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal Reproducible Example (MRE)
      description: |
        Please provide a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
        as a copy-pastable code snippet if possible. If not, describe steps to
        reproduce the behavior. Please enclose code blocks within triple backticks.
      placeholder: |
        ```python
        # Copy-pastable, executable code here
        ```

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happens. Please enclose code output / error messages within triple backticks.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen. Please cite (with links) relevant documentation about what should happen.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
