name: Run test notebooks

on:
  workflow_dispatch:
    inputs:
      target_backend:
        description: 'Backend environment to run notebooks against'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - staging

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        notebook: [
          "demo/4. advanced demo.ipynb",
          "google_qmem_experiment/decode.ipynb",
          "google_qmem_experiment/noise_analysis.ipynb",
          "qmem/rotated_planar_quantum_memory_plots.ipynb",
          "simulation/shot_analysis.ipynb",
          "simulation/stim_simulation.ipynb",
          "simulation/ac_decoding.ipynb",
          "simulation/leakage_demo.ipynb"
        ]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter ipykernel nbconvert
          python -m pip install ./ ./deltakit-core ./deltakit-circuit ./deltakit-decode ./deltakit-explorer

      - name: Run Jupyter notebooks on prod
        if: ${{ inputs.target_backend == 'prod' || inputs.target_backend == ''}}
        env:
            DELTAKIT_TOKEN: ${{ secrets.DELTAKIT_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute --inplace --debug "docs/examples/notebooks/${{ matrix.notebook }}"

      - name: Run Jupyter notebooks on staging
        if: ${{ inputs.target_backend == 'staging' }}
        env:
            DELTAKIT_TOKEN: ${{ secrets.DELTAKIT_TOKEN_STAGING }}
            DELTAKIT_SERVER: ${{ secrets.STAGING_URL }}
        run: |
          jupyter nbconvert --to notebook --execute --inplace --debug "docs/examples/notebooks/${{ matrix.notebook }}"
 
